export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_BUYERS_SUCCESS = 'LOAD_BUYERS_SUCCESS';
export const UPDATE_BUYER_SUCCESS = 'UPDATE_BUYER_SUCCESS';
export const CREATE_BUYER_SUCCESS = 'CREATE_BUYER_SUCCESS';
export const LOAD_ORDER_SUCCESS = 'LOAD_ORDER_SUCCESS';
