export const ADD_BUYER = 'ADD_BUYER';
export const LOAD_BUYERS_SUCCESS = 'LOAD_BUYERS_SUCCESS';
export const UPDATE_BUYER_SUCCESS = 'UPDATE_BUYER_SUCCESS';
export const CREATE_BUYER_SUCCESS = 'CREATE_BUYER_SUCCESS';
